# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bc7c390858dfe72c6a247d804c7424826bb858b9376b916b8d147bb78f2990c13efaadcc665110b6740bb666f65898f89dfea07589fd867b324f1df90794a56a

test:
  secret_key_base: 5b2f1cf182c9b8142ebc48043d5f179b70af4ed52b7519ac577bb5909087f4751fd73e8173b402cdda5330dae3c5b5d26fa7dcc0381410a215a9b0226cab19ac

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
